# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from mz_backend.views import *

urlpatterns = patterns('',
                       url(r'^login/$', admin_login, name="admin_login"),
                       url(r'^index/$', admin_index_view, name="admin_index_view"),
                       url(r'^logout/$', admin_logout, name="admin_logout"),
                       url(r'^update/video/length/view/$', update_video_length_view, name="update_video_length_view"),
                       url(r'^update/video/length/lessons/$', get_lessons_list, name="get_lessons_list"),
                       url(r'^update/video/length/(?P<lesson_id>[\d]+)/$', update_video_length, name="update_video_length"),
                       url(r'^join/class/step1/$', join_class_1_view, name="join_class_1_view"),
                       url(r'^join/class/step2/$', join_class_2_view, name="join_class_2_view"),
                       url(r'^join/class/save/$', join_class_save, name="join_class_save"),
                       url(r'^quit/class/step1/$', quit_class_1_view, name="quit_class_1_view"),
                       url(r'^quit/class/step2/$', quit_class_2_view, name="quit_class_2_view"),
                       url(r'^quit/class/save/$', quit_class_save, name="quit_class_save"),
                       url(r'^change/class/step1/$', change_class_1_view, name="change_class_1_view"),
                       url(r'^change/class/step2/$', change_class_2_view, name="change_class_2_view"),
                       url(r'^change/class/save/$', change_class_save, name="change_class_save"),
                       url(r'^order/list/$', order_list_view, name="order_list_view"),
                       url(r'^coupon/list/$', coupon_list_view, name="coupon_list_view"),
                       url(r'^coupon/list/details/(?P<coupon_id>[\d]+)/$', coupon_list_details, name="coupon_list_details"),
                       url(r'^main/$', admin_main, name="admin_main"),
                       url(r'^sync/avatar/view/$', sync_avatar_view, name="sync_avatar_view"),
                       url(r'^sync/avatar/users/$', get_user_list, name="get_user_list"),
                       url(r'^sync/avatar/sync/$', sync_avatar, name="sync_avatar"),
                       url(r'^recommend/reading/index/$', recommend_reading_index, name="recommend_reading_index"),
                       url(r'^recommend/reading/add/$', recommend_reading_edit, name="recommend_reading_add"),
                       url(r'^recommend/reading/edit/(?P<reading_id>[\d]+)/$', recommend_reading_edit, name="recommend_reading_edit"),
                       url(r'^recommend/reading/delete/(?P<reading_id>[\d]+)/$', recommend_reading_delete, name="recommend_reading_delete"),
                       url(r'^update/uuid/$', update_uuid, name="update_uuid"),
                       url(r'^liveroom/list/$', live_room_list, name="live_room_list"),
                       url(r'^create/liveroom/$', create_live_room, name="create_live_room"),
                       url(r'^update/liveroom/$', update_live_room, name="update_live_room"),
                       url(r'^msgbox/list/$', msg_send_list, name="msg_send_list"),
                       url(r'^create/msgbox/$', create_msg, name="create_msg"),
                       url(r'^acauser/list/$', acauser_list, name="acauser_list"),
                       url(r'^acauser/import/$', acauser_import, name="acauser_import"),
                       url(r'^acauser/export/$', acauser_export, name="acauser_export"),
                       url(r'^acauser/delete/$', acauser_delete, name="acauser_delete"),
                       url(r'^clear/cache/$', clear_cache, name="clear_cache"),
  )