# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from mz_user import views

urlpatterns = patterns('',
                       url(r'^password/find/$',views.find_password,name='find_password'),
                       url(r'^password/find/mobile/$',views.find_password_mobile_code,name='find_password_mobile_code'),
                       url(r'^password/reset/update/view/$',views.update_reset_password_view,name='update_reset_password_view'),
                       url(r'^password/reset/update/$',views.update_reset_password,name='update_reset_password'),
                       url(r'^password/reset/(?P<account>[^/]+)/(?P<code>[^/]+)/$',views.reset_password,name='reset_password'),
                       url(r'^active/(?P<email>[^/]+)/(?P<code>[^/]+)/$',views.do_active,name='do_active'),
                       url(r'^register/email/$',views.email_register,name='email_register'),
                       url(r'^register/mobile/$',views.mobile_register,name='mobile_register'),
                       url(r'^register/mobile/sendsms/$',views.send_sms_code,name='send_sms_code'),
                       url(r'^login/$',views.user_login,name='login'),
                       url(r'^logout/$',views.user_logout,name='logout'),
                       url(r'^center/$',views.user_center,name='user_center'),
                       url(r'^student/$',views.student_mycourse_view,name='student_center'),
                       url(r'^student/favorite/$',views.student_myfavorite_view,name='student_myfavorite'),
                       url(r'^student/certificate/$',views.student_mycertificate_view,name='student_mycertificate'),
                       url(r'^student/certificate/download/(?P<certificate_id>[\d]+)/$',views.student_mycertificate_download,name='student_mycertificate_download'),
                       url(r'^student/avatar/upload/$', views.avatar_upload,name="avatar_upload"),
                       url(r'^student/avatar/crop/$', views.avatar_crop,name="avatar_crop"),
                       url(r'^teacher/$',views.teacher_myclass_view, name='teacher_center'),
                       url(r'^message/$',views.user_mymessage_view,name='user_mymessage'),
                       url(r'^info/$',views.user_myinfo_view,name='user_myinfo'),
                       url(r'^info/save/$',views.user_info_save,name='user_info_save'),
                       url(r'^info/email/$',views.user_info_email,name='user_info_email'),
                       url(r'^city/list/$',views.city_list,name='city_list'),
                       url(r'^change/password/$',views.change_password,name='change_password'),
                       url(r'^get/careercourse/$',views.get_careercourse,name='get_careercourse'),
                       url(r'^mobile/update/$',views.user_update_mobile,name='user_update_mobile'),
                       url(r'^mobile/update/sendsms/$',views.user_update_mobile_sendsms,name='user_update_mobile_sendsms'),
                       url(r'^email/update/$',views.user_update_email,name='user_update_email'),
                       url(r'^create/class/save/$',views.create_class_save,name='create_class_save'),
                       url(r'^mobile/register/$',views.mobile_register_view,name='mobile_register_view'),
                       url(r'^mobile/login/$',views.mobile_login_view,name='mobile_login_view'),
                       url(r'^ucsynlogin/destory/$',views.destory_ucsynlogin_session,name='destory_ucsynlogin_session'),
                       url(r'^goto/bbs/$',views.user_goto_bbs,name='user_goto_bbs'),
)
